# Generated by Django 5.0.3 on 2024-04-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_workstation_country_workstation_county_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("contract_start_date", models.DateField(blank=True, null=True)),
                (
                    "location_description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("guards_posted", models.IntegerField(default=0)),
                ("guards_needed", models.IntegerField(default=0)),
                (
                    "work_shift",
                    models.CharField(
                        choices=[
                            ("Day Shift", "Day Shift"),
                            ("Night Shift", "Night Shift"),
                            ("24 Hours Shift", "24 Hours Shift"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "postal_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("town", models.CharField(blank=True, max_length=255, null=True)),
                ("county", models.CharField(max_length=255, null=True)),
                ("country", models.CharField(max_length=255, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="workstation",
            name="contract_start_date",
        ),
        migrations.RemoveField(
            model_name="workstation",
            name="country",
        ),
        migrations.RemoveField(
            model_name="workstation",
            name="county",
        ),
        migrations.RemoveField(
            model_name="workstation",
            name="email",
        ),
        migrations.RemoveField(
            model_name="workstation",
            name="location_description",
        ),
        migrations.RemoveField(
            model_name="workstation",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="workstation",
            name="postal_address",
        ),
        migrations.RemoveField(
            model_name="workstation",
            name="town",
        ),
    ]
