# Generated by Django 5.0.6 on 2024-06-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_workstation_client"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("job_group", models.CharField(max_length=255)),
                ("daily_rate", models.DecimalField(decimal_places=2, max_digits=100)),
                ("overtime", models.DecimalField(decimal_places=0, max_digits=100)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
