# Generated by Django 5.0.6 on 2024-07-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_taxband"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentconfig",
            name="monthly_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name="paymentconfig",
            name="daily_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name="paymentconfig",
            name="overtime",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=100),
        ),
    ]
