# Generated by Django 5.0.6 on 2024-07-21 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0029_delete_bankinformation"),
        ("payments", "0008_payslip"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "bank_name",
                    models.CharField(default="Equity Bank Kenya", max_length=255),
                ),
                ("branch_name", models.CharField(max_length=255)),
                ("account_name", models.CharField(max_length=255)),
                ("account_type", models.CharField(max_length=255, null=True)),
                ("account_number", models.CharField(max_length=255)),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bankingdetails",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
