# Generated by Django 5.0.3 on 2024-03-27 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=100),
                ),
                ("quantity", models.IntegerField(default=0)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Uniform", "Uniform"),
                            ("Electronics", "Electronics"),
                        ],
                        max_length=255,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EquipmentIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("quantity", models.IntegerField(default=0)),
                ("date_issued", models.DateField(auto_now_add=True)),
                ("return_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Returned", "Returned"),
                            ("Pending", "Pending"),
                            ("Lost", "Lost"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="equipments.equipment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
