# Generated by Django 5.0.3 on 2024-03-28 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipments", "0002_equipment_issued"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="equipmentissue",
            name="issued_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equipmentissuers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
