# Generated by Django 5.0.3 on 2024-04-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipments", "0005_equipmentissuelog_equipmentlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipmentissue",
            name="condition",
            field=models.CharField(
                choices=[("New", "New"), ("Used", "Used"), ("Faulty", "Faulty")],
                max_length=255,
                null=True,
            ),
        ),
    ]
