# Generated by Django 5.0.3 on 2024-04-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipments", "0006_equipmentissue_condition"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipmentissue",
            name="condition",
        ),
        migrations.RemoveField(
            model_name="equipmentissue",
            name="return_date",
        ),
        migrations.AddField(
            model_name="equipmentissue",
            name="baton_issued",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="equipmentissue",
            name="belt_issued",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="equipmentissue",
            name="boots_issued",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="equipmentissue",
            name="chest_guard_issued",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="equipmentissue",
            name="head_cap_issued",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="equipmentissue",
            name="shirt_issued",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="equipmentissue",
            name="shoes_issued",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="equipmentissue",
            name="sweater_issued",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="category",
            field=models.CharField(
                choices=[
                    ("Shirt", "Shirt"),
                    ("Head Cap", "Head Cap"),
                    ("Belt", "Belt"),
                    ("Trousers", "Trousers"),
                    ("Chest Guard", "Chest Guard"),
                    ("Shoes", "Shoes"),
                    ("Boots", "Boots"),
                    ("Sweater", "Sweater"),
                    ("Baton", "Baton"),
                ],
                max_length=255,
            ),
        ),
    ]
