# Generated by Django 5.0.3 on 2024-04-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipments", "0007_remove_equipmentissue_condition_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipmentissue",
            name="date_issued",
            field=models.DateField(null=True),
        ),
    ]
