# Generated by Django 5.0.3 on 2024-04-06 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("equipments", "0008_alter_equipmentissue_date_issued"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipmentissue",
            name="equipment",
        ),
        migrations.RemoveField(
            model_name="equipmentissue",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="equipmentissue",
            name="status",
        ),
    ]
