# Generated by Django 5.0.3 on 2024-04-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipments", "0009_remove_equipmentissue_equipment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipmentissue",
            name="trouser_issued",
            field=models.BooleanField(default=False),
        ),
    ]
