# Generated by Django 5.0.6 on 2024-07-21 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipments", "0012_vehicle_vehicle_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="vehicle_type",
            field=models.CharField(
                choices=[("Vehicle", "Vehicle"), ("Motorbike", "Motorbike")],
                max_length=255,
            ),
        ),
    ]
