# Generated by Django 5.0.6 on 2024-07-26 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipments", "0013_alter_vehicle_vehicle_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiclefuelhistory",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fuelingrecords",
                to="equipments.vehicle",
            ),
        ),
    ]
