# Generated by Django 5.0.6 on 2024-07-26 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipments", "0014_alter_vehiclefuelhistory_vehicle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicleservicehistory",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="servicerecords",
                to="equipments.vehicle",
            ),
        ),
    ]
