# Generated by Django 5.0.6 on 2024-07-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipments", "0015_alter_vehicleservicehistory_vehicle"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="vehicle_status",
            field=models.CharField(
                choices=[
                    ("Good", "Good"),
                    ("Retired", "Retired"),
                    ("Broken", "Broken"),
                ],
                default="Good",
                max_length=255,
            ),
        ),
    ]
