# Generated by Django 5.0.3 on 2024-03-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="position",
            field=models.CharField(
                choices=[
                    ("Security Manager", "Security Manager"),
                    ("Security Guard", "Security Guard"),
                ],
                max_length=255,
            ),
        ),
    ]
