# Generated by Django 5.0.3 on 2024-03-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="basic_salary",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name="user",
            name="nhif_number",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="nssf_number",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
