# Generated by Django 5.0.3 on 2024-03-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_basic_salary_user_nhif_number_user_nssf_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="chief_letter",
            field=models.FileField(blank=True, null=True, upload_to="chief_letters/"),
        ),
        migrations.AddField(
            model_name="user",
            name="passport_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="passport_photos/"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="police_clearance",
            field=models.FileField(
                blank=True, null=True, upload_to="police_clearances/"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="recommendation_letter",
            field=models.FileField(
                blank=True, null=True, upload_to="recommended_letters/"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="scanned_id",
            field=models.FileField(blank=True, null=True, upload_to="scanned_ids/"),
        ),
    ]
