# Generated by Django 5.0.3 on 2024-03-29 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_workstation_country_workstation_county_and_more"),
        ("users", "0004_user_chief_letter_user_passport_photo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="workstation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workstationsguards",
                to="core.workstation",
            ),
        ),
    ]
