# Generated by Django 5.0.3 on 2024-03-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_workstation"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="daily_rate",
            field=models.DecimalField(decimal_places=2, default=350, max_digits=100),
        ),
    ]
