# Generated by Django 5.0.3 on 2024-04-11 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_workstation_client"),
        ("users", "0006_user_daily_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="workstation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clientsguards",
                to="core.workstation",
            ),
        ),
    ]
