# Generated by Django 5.0.3 on 2024-04-11 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_workstation_client"),
        ("users", "0007_alter_user_workstation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="workstation",
        ),
        migrations.AddField(
            model_name="user",
            name="client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clientsguards",
                to="core.client",
            ),
        ),
    ]
