# Generated by Django 5.0.3 on 2024-04-11 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_remove_user_workstation_user_client"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="chief_letter",
        ),
        migrations.RemoveField(
            model_name="user",
            name="passport_photo",
        ),
        migrations.RemoveField(
            model_name="user",
            name="police_clearance",
        ),
        migrations.RemoveField(
            model_name="user",
            name="recommendation_letter",
        ),
        migrations.RemoveField(
            model_name="user",
            name="scanned_id",
        ),
    ]
