# Generated by Django 5.0.6 on 2024-06-01 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_paymentconfig"),
        ("users", "0009_remove_user_chief_letter_remove_user_passport_photo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="job_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.paymentconfig",
            ),
        ),
    ]
