# Generated by Django 5.0.6 on 2024-06-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_user_job_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="passport_photo",
            field=models.ImageField(null=True, upload_to="passport_photos/"),
        ),
    ]
