# Generated by Django 5.0.6 on 2024-06-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_user_passport_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="position",
            field=models.CharField(
                choices=[
                    ("Security Manager", "Security Manager"),
                    ("Security Guard", "Security Guard"),
                    ("CCTV Installer", "CCTV Installer"),
                ],
                max_length=255,
            ),
        ),
    ]
