# Generated by Django 5.0.6 on 2024-06-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_alter_user_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[
                    ("Available", "Available"),
                    ("On Leave", "On Leave"),
                    ("Suspended", "Suspended"),
                ],
                default="Available",
                max_length=255,
            ),
        ),
    ]
