# Generated by Django 5.0.6 on 2024-06-03 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_alter_user_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="nssf_number",
            new_name="kra_pin",
        ),
    ]
