# Generated by Django 5.0.6 on 2024-06-05 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_taxband"),
        ("users", "0017_user_nssf_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="workstation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.workstation",
            ),
        ),
    ]
