# Generated by Django 5.0.6 on 2024-07-21 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_jobrole"),
        ("users", "0021_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.client",
            ),
        ),
    ]
