# Generated by Django 5.0.6 on 2024-07-21 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_jobrole"),
        ("users", "0022_alter_user_client"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="client",
        ),
        migrations.RemoveField(
            model_name="user",
            name="daily_rate",
        ),
        migrations.RemoveField(
            model_name="user",
            name="job_category",
        ),
        migrations.RemoveField(
            model_name="user",
            name="passport_photo",
        ),
        migrations.RemoveField(
            model_name="user",
            name="status",
        ),
        migrations.RemoveField(
            model_name="user",
            name="workstation",
        ),
        migrations.AlterField(
            model_name="user",
            name="position",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staffpositions",
                to="core.jobrole",
            ),
        ),
    ]
