# Generated by Django 5.0.6 on 2024-06-01 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0006_workstation_client"),
    ]

    operations = [
        migrations.CreateModel(
            name="Visitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("id_number", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=255)),
                ("office_visiting", models.CharField(max_length=500, null=True)),
                ("visitation_reason", models.CharField(max_length=1000, null=True)),
                ("car_plate_number", models.CharField(max_length=255, null=True)),
                ("car_model", models.CharField(max_length=255, null=True)),
                ("car_colour", models.CharField(max_length=255, null=True)),
                (
                    "place",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.client",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("checkin_time", models.DateTimeField()),
                ("checkout_time", models.DateTimeField(null=True)),
                (
                    "visitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="visitors.visitor",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
