# Generated by Django 5.0.6 on 2024-06-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visitors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitor",
            name="gender",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
