# Generated by Django 5.0.6 on 2024-07-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeleave",
            name="status",
            field=models.CharField(
                choices=[
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                    ("Pending Review", "Pending Review"),
                    ("Complete", "Complete"),
                ],
                default="Pending Review",
                max_length=255,
            ),
        ),
    ]
