# Generated by Django 4.2 on 2024-08-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0002_alter_attendance_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="checkin_time",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
