# Generated by Django 5.0.3 on 2024-03-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_alter_attendance_checkin_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="checked_in",
            field=models.BooleanField(default=False),
        ),
    ]
