# Generated by Django 5.0.3 on 2024-03-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_attendance_checked_in"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="checkin_time",
            field=models.DateTimeField(null=True),
        ),
    ]
