# Generated by Django 5.0.3 on 2024-03-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0004_alter_attendance_checkin_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("Absent", "Absent"), ("Present", "Present")],
                max_length=255,
                null=True,
            ),
        ),
    ]
