# Generated by Django 5.0.3 on 2024-03-27 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0005_attendance_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attendance",
            old_name="checked_in",
            new_name="marked",
        ),
    ]
