# Generated by Django 5.0.3 on 2024-04-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0014_alter_bankinformation_employee"),
    ]

    operations = [
        migrations.AddField(
            model_name="educationinformation",
            name="start_year",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="nextofkin",
            name="gender",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
