# Generated by Django 5.0.3 on 2024-04-11 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "employees",
            "0019_rename_recommendation_letter_employeedocument_referee_letter",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="employeedocument",
            old_name="chief_letter",
            new_name="Chief Letter",
        ),
        migrations.RenameField(
            model_name="employeedocument",
            old_name="college_certificate",
            new_name="College Certificate",
        ),
        migrations.RenameField(
            model_name="employeedocument",
            old_name="kcpe_certificate",
            new_name="KCPE Certificate",
        ),
        migrations.RenameField(
            model_name="employeedocument",
            old_name="kcse_certificate",
            new_name="KCSE Certificate",
        ),
        migrations.RenameField(
            model_name="employeedocument",
            old_name="kra_certificate",
            new_name="KRA Certificate",
        ),
        migrations.RenameField(
            model_name="employeedocument",
            old_name="police_clearance",
            new_name="Police Clearance",
        ),
        migrations.RenameField(
            model_name="employeedocument",
            old_name="referee_letter",
            new_name="Referee Letter",
        ),
        migrations.RenameField(
            model_name="employeedocument",
            old_name="scanned_id",
            new_name="Scanned ID",
        ),
    ]
