# Generated by Django 5.0.3 on 2024-04-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0022_alter_employeedocument_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeleave",
            name="leave_type",
            field=models.CharField(
                choices=[
                    ("Sick Leave", "Sick Leave"),
                    ("Emergency Leave", "Emergency Leave"),
                    ("Normal Leave", "Normal Leave"),
                ],
                max_length=255,
            ),
        ),
    ]
