# Generated by Django 5.0.6 on 2024-07-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0023_alter_employeeleave_leave_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[("Absent", "Absent"), ("Present", "Present")],
                default="Present",
                max_length=255,
            ),
        ),
    ]
