# Generated by Django 5.0.6 on 2024-07-20 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0024_alter_attendance_status"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmployeeLeave",
        ),
    ]
