# Generated by Django 5.0.6 on 2024-07-21 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0025_delete_employeeleave"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Attendance",
        ),
    ]
