# Generated by Django 5.0.6 on 2024-07-21 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_jobrole"),
        ("employees", "0026_delete_attendance"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=255
                    ),
                ),
                ("phone_number", models.CharField(max_length=255)),
                ("id_number", models.CharField(max_length=255, null=True)),
                ("nhif_number", models.CharField(max_length=255, null=True)),
                ("nssf_number", models.CharField(max_length=255, null=True)),
                ("kra_pin", models.CharField(max_length=255, null=True)),
                ("postal_address", models.CharField(max_length=255, null=True)),
                ("physical_address", models.CharField(max_length=255, null=True)),
                ("town", models.CharField(max_length=255, null=True)),
                ("county", models.CharField(max_length=255, null=True)),
                ("country", models.CharField(max_length=255, null=True)),
                (
                    "basic_salary",
                    models.DecimalField(decimal_places=2, default=0, max_digits=100),
                ),
                (
                    "daily_rate",
                    models.DecimalField(decimal_places=2, default=350, max_digits=100),
                ),
                (
                    "passport_photo",
                    models.ImageField(null=True, upload_to="passport_photos/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending Approval", "Pending Approval"),
                            ("Declined", "Declined"),
                            ("Available", "Available"),
                            ("On Leave", "On Leave"),
                            ("Suspended", "Suspended"),
                        ],
                        default="Available",
                        max_length=255,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clientsguards",
                        to="core.client",
                    ),
                ),
                (
                    "job_category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.paymentconfig",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.jobrole",
                    ),
                ),
                (
                    "workstation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.workstation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
