# Generated by Django 5.0.6 on 2024-07-21 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0027_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankinformation",
            name="employee",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bankingdetails",
                to="employees.employee",
            ),
        ),
        migrations.AlterField(
            model_name="educationinformation",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="educationdetails",
                to="employees.employee",
            ),
        ),
        migrations.AlterField(
            model_name="employeedocument",
            name="employee",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employeedocuments",
                to="employees.employee",
            ),
        ),
        migrations.AlterField(
            model_name="nextofkin",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nextofkins",
                to="employees.employee",
            ),
        ),
    ]
