# Generated by Django 5.0.6 on 2024-07-21 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0028_alter_bankinformation_employee_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BankInformation",
        ),
    ]
