# Generated by Django 5.0.6 on 2024-07-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0029_delete_bankinformation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending Approval", "Pending Approval"),
                    ("Declined", "Declined"),
                    ("Available", "Available"),
                    ("On Leave", "On Leave"),
                    ("Suspended", "Suspended"),
                ],
                default="Pending Approval",
                max_length=255,
            ),
        ),
    ]
