# Generated by Django 5.0.6 on 2024-07-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0030_alter_employee_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="residence",
            field=models.TextField(null=True),
        ),
    ]
