# Generated by Django 5.0.6 on 2024-07-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0031_employee_residence"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="workshift",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
